export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const RECOVER_SUCCESS = "RECOVER_SUCCESS";
export const RECOVER_FAIL = "RECOVER_FAIL";

export const RESET_SUCCESS = "RESET_SUCCESS";
export const RESET_FAIL = "RESET_FAIL";

export const VERIFY_SUCCESS = "VERIFY_SUCCESS";
export const VERIFY_FAIL = "VERIFY_FAIL";

export const CHAT_CREATE_SUCCESS = " CHAT_CREATE_SUCCESS ";
export const CHAT_CREATE_FAIL = " CHAT_CREATE_FAIL";

export const CHAT_LOAD_SUCCESS = "CHAT_LOAD_SUCCESS";
export const CHAT_LOAD_FAIL = "CHAT_LOAD_FAIL";
export const CHAT_EMPTY_SET = "CHAT_EMPTY_SET";

export const PRODUCT_SUCCESS = "PRODUCT_SUCCESS";
export const PRODUCT_FAIL = "PRODUCT_FAIL";

export const PRODUCT_UPDATE_SUCCESS = "PRODUCT_UPDATE_SUCCESS";
export const PRODUCT_UPDATE_FAIL = "PRODUCT_UPDATE_FAIL";

export const PRODUCT_LOAD_SUCCESS = "PRODUCT_LOAD_SUCCESS";
export const PRODUCT_LOAD_FAIL = "PRODUCT_LOAD_FAIL";
export const PRODUCT_EMPTY_SET = "PRODUCT_EMPTY_SET";

export const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS";
export const PRODUCT_DELETE_FAIL = "PRODUCT_DELETE_FAIL";

export const PRODUCT_SINGLE_LOAD_SUCCESS = "PRODUCT_SINGLE_LOAD_SUCCESS";
export const PRODUCT_SINGLE_LOAD_FAIL = "PRODUCT_SINGLE_LOAD_FAIL";

export const CATEGORY_SUCCESS = "CATEGORY_SUCCESS";
export const CATEGORY_FAIL = "CATEGORY_FAIL";

export const CATEGORY_UPDATE_SUCCESS = "CATEGORY_UPDATE_SUCCESS";
export const CATEGORY_UPDATE_FAIL = "CATEGORY_UPDATE_FAIL";

export const CATEGORY_DELETE_SUCCESS = "CATEGORY_DELETE_SUCCESS";
export const CATEGORY_DELETE_FAIL = "CATEGORY_DELETE_FAIL";

export const CATEGORY_LOAD_SUCCESS = "CATEGORY_LOAD_SUCCESS";
export const CATEGORY_LOAD_FAIL = "CATEGORY_LOAD_FAIL";
export const CATEGORY_EMPTY_SET = "CATEGORY_EMPTY_SET";

export const CATEGORY_SINGLE_LOAD_SUCCESS = "CATEGORY_SINGLE_LOAD_SUCCESS";
export const CATEGORY_SINGLE_LOAD_FAIL = "CATEGORY_SINGLE_LOAD_FAIL";

export const SUBCATEGORY_SUCCESS = "SUBCATEGORY_SUCCESS";
export const SUBCATEGORY_FAIL = "SUBCATEGORY_FAIL";

export const SUBCATEGORY_LOAD_SUCCESS = "SUBCATEGORY_LOAD_SUCCESS";
export const SUBCATEGORY_LOAD_FAIL = "SUBCATEGORY_LOAD_FAIL";
export const SUBCATEGORY_EMPTY_SET = "SUBCATEGORY_EMPTY_SET";

export const SUBCATEGORY_UPDATE_SUCCESS = "SUBCATEGORY_UPDATE_SUCCESS";
export const SUBCATEGORY_UPDATE_FAIL = "SUBCATEGORY_UPDATE_FAIL";

export const SUBCATEGORY_DELETE_SUCCESS = "SUBCATEGORY_DELETE_SUCCESS";
export const SUBCATEGORY_DELETE_FAIL = "SUBCATEGORY_DELETE_FAIL";

export const CART_CREATE_SUCCESS = " CART_CREATE_SUCCESS";
export const CART_CREATE_FAIL = "CART_CREATE_FAIL";

export const CART_INCREMENT = "CART_INCREMENT";
export const CART_INCREMENT_FAIL = "CART_INCREMENT_FAIL";

export const CART_LOAD_SUCCESS = "CART_LOAD_SUCCESS";
export const CART_LOAD_FAIL = "CART_LOAD_FAIL";

export const CART_DELETE_SUCCESS = "CART_DELETE_SUCCESS";
export const CART_DELETE_FAIL = "CART_DELETE_FAIL";

export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";

export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const RELATED_PRODUCT_LOAD_SUCCESS = "RELATED_PRODUCT_LOAD_SUCCESS";
export const RELATED_PRODUCT_LOAD_FAIL = "RELATED_PRODUCT_LOAD_FAIL";
export const RELATED_PRODUCT_EMPTY_SET = "RELATED_PRODUCT_EMPTY_SET";

export const WISHLIST_LOAD_SUCCESS = " WISHLIST_LOAD_SUCCESS";
export const WISHLIST_LOAD_FAIL = " WISHLIST_LOAD_FAIL";
