export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const RECOVER_SUCCESS = 'RECOVER_SUCCESS';
export const RECOVER_FAIL = 'RECOVER_FAIL';

export const RESET_SUCCESS = 'RESET_SUCCESS';
export const RESET_FAIL = 'RESET_FAIL';

export const PRODUCT_SUCCESS = 'PRODUCT_SUCCESS';
export const PRODUCT_FAIL = 'PRODUCT_FAIL';

export const PRODUCT_LOAD_SUCCESS = 'PRODUCT_LOAD_SUCCESS';
export const PRODUCT_LOAD_FAIL = 'PRODUCT_LOAD_FAIL';

export const CATEGORY_SUCCESS = 'CATEGORY_SUCCESS';
export const CATEGORY_FAIL = 'CATEGORY_FAIL';

export const CATEGORY_LOAD_SUCCESS = 'CATEGORY_LOAD_SUCCESS';
export const CATEGORY_LOAD_FAIL = 'CATEGORY_LOAD_FAIL';

export const SUBCATEGORY_SUCCESS = 'SUBCATEGORY_SUCCESS';
export const SUBCATEGORY_FAIL = 'SUBCATEGORY_FAIL';

export const SUBCATEGORY_LOAD_SUCCESS = 'SUBCATEGORY_LOAD_SUCCESS';
export const SUBCATEGORY_LOAD_FAIL = 'SUBCATEGORY_LOAD_FAIL';
export const SUBCATEGORY_EMPTY_SET = 'SUBCATEGORY_EMPTY_SET';

export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
